sudo: false
language: cpp
compiler:
    - gcc
env:
    - FX_VERSION="49.0.2"
matrix:
    fast_finish: true
    #allow_failures:
    #    - env: FX_CHANNEL="beta"
notifications:
    email: false
install:
    - if [ $FX_VERSION = "49.0.2" ]; then
        wget -O tarball "https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-release-linux64-add-on-devel/1476892163/firefox-49.0.2.en-US.linux-x86_64-add-on-devel.tar.bz2";
      fi
    - tar xf tarball
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - test/runtests.sh -x firefox/firefox
